export const CACHE_SEARCH_RESULTS = "CACHE_SEARCH_RESULTS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const LOAD_CACHED_RESULTS = "LOAD_CACHED_RESULTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
