export const CACHE_SEARCH_RESULTS = "CACHE_SEARCH_RESULTS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const LOAD_CACHED_RESULTS = "LOAD_CACHED_RESULTS";
export const TOGGLE_CART_ITEM = "TOGGLE_CART_ITEM";
