export const CACHE_SEARCH_RESULTS = "CACHE_SEARCH_RESULTS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_LAST_QUERY = "SET_LAST_QUERY";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHANGE_SERVINGS = "CHANGE_SERVINGS";
export const START_FETCHING_SEARCH = "START_FETCHING_SEARCH";
